spring.application.name=edusmart-backend
spring.mongodb.uri=mongodb+srv://chriguimohamed:edusmart123@edusmart.q8e3feo.mongodb.net/?appName=edusmart
spring.mongodb.database=edusmart
server.port=8080
jwt.secret=edusmart_super_secret_key_2026_very_long_string_for_security
jwt.expiration=86400000


